### ISSUE TITLE
Got 'Invalid argument' error message while running boostrap on centos6

### ISSUE THREAD

**Issue by abajwa-hw** [seanorama/ambari-bootstrap#8]
Running below on centos 6
sudo yum -y install git
git clone https://github.com/seanorama/ambari-bootstrap
cd ambari-bootstrap
sudo install_ambari_server=true install_ambari-agent=true ./ambari-bootstrap.sh

Saw the below:
/usr/local/sbin/ambari-thp-disable.sh: line 12: echo: write error: Invalid argument
 Info: Disabling iptables

**Comment by seanorama** [comment]
Fixed. Did it a while back but wasn't tracking issues here.
